#!/usr/bin/env bats
# E2E tests for plist clean/smudge filters and the adopt/prompt machinery.
#
# These exercise the real glue between dodot, git, and the shell — the
# unit-test suite covers the conversion logic itself, but cannot prove
# that:
#
#   - .git/config gets the right [filter "dodot-plist"] block,
#   - git actually invokes our filters on add/checkout,
#   - canonical XML lands in the index when a binary is staged,
#   - smudge produces a binary when XML is checked out,
#   - `required = true` makes corrupt input fail loudly,
#   - dodot adopt + git filters compose end-to-end on commit,
#   - the prompt registry persists across invocations.
#
# The plist binary fixtures are generated by `dodot plist smudge` itself.
# Determinism is guaranteed by the §4.3 unit test, so using dodot's own
# subcommand to materialize binaries doesn't compromise these tests'
# value as integration coverage.

setup() {
    load helpers/setup
    sandbox_setup

    # Most filter tests need to ensure dodot is on PATH for git to
    # invoke. The sandbox's git inherits our PATH, but explicit is
    # better than implicit — failures here are obscure to debug.
    PATH="$(dirname "$DODOT_BIN"):$PATH"
    export PATH

    # Configure git identity so commits succeed. Sandbox repos are
    # ephemeral so we set this per-test rather than globally.
    git -C "$DOTFILES_ROOT" config user.email "test@dodot.invalid"
    git -C "$DOTFILES_ROOT" config user.name "dodot e2e"
}

teardown() {
    sandbox_teardown
}

# ── Fixture helpers ─────────────────────────────────────────────

# Materialize a binary plist in the working tree from XML on stdin.
# Uses `dodot plist smudge` (proven deterministic in unit tests).
write_binary_plist() {
    local path="$1"
    local xml="$2"
    mkdir -p "$(dirname "$path")"
    printf '%s' "$xml" | "$DODOT_BIN" plist smudge > "$path"
}

# A small XML plist whose dictionary keys are NOT alphabetised, so we
# can prove the clean filter sorts them on commit.
SHUFFLED_PLIST_XML='<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>zebra</key>
	<string>last</string>
	<key>apple</key>
	<string>first</string>
	<key>middle</key>
	<integer>42</integer>
</dict>
</plist>'

# Wire .gitattributes to the filter and register the filter in
# .git/config — the canonical setup that real users would have after
# running `dodot git-install-filters` plus committing the .gitattributes
# line.
configure_plist_filter() {
    git -C "$DOTFILES_ROOT" config filter.dodot-plist.clean  "$DODOT_BIN plist clean"
    git -C "$DOTFILES_ROOT" config filter.dodot-plist.smudge "$DODOT_BIN plist smudge"
    git -C "$DOTFILES_ROOT" config filter.dodot-plist.required true
    echo '*.plist filter=dodot-plist' > "$DOTFILES_ROOT/.gitattributes"
}

# ── git-install-filters ─────────────────────────────────────────

@test "git-install-filters writes the [filter \"dodot-plist\"] block to .git/config" {
    run dodot git-install-filters
    [ "$status" -eq 0 ]
    assert_output_contains "Installed plist clean/smudge filters"

    # Verify the actual config file content via git, not by parsing
    # .git/config — git config is the authoritative interface.
    local clean smudge required
    clean="$(git -C "$DOTFILES_ROOT" config --get filter.dodot-plist.clean)"
    smudge="$(git -C "$DOTFILES_ROOT" config --get filter.dodot-plist.smudge)"
    required="$(git -C "$DOTFILES_ROOT" config --get filter.dodot-plist.required)"
    [ "$clean"    = "dodot plist clean" ]
    [ "$smudge"   = "dodot plist smudge" ]
    [ "$required" = "true" ]
}

@test "git-install-filters is idempotent on re-run" {
    dodot git-install-filters
    run dodot git-install-filters
    [ "$status" -eq 0 ]
    assert_output_contains "already installed"

    # Re-run must not duplicate the entries — `--get` returns a single
    # value or fails with multiple-values.
    git -C "$DOTFILES_ROOT" config --get filter.dodot-plist.clean
}

@test "git-show-filters reports installed=true once the filter is registered" {
    # First with no filter — output should NOT claim it's installed.
    run dodot git-show-filters
    [ "$status" -eq 0 ]
    assert_output_contains "filter \"dodot-plist\""
    assert_output_not_contains "already installed"

    dodot git-install-filters
    run dodot git-show-filters
    [ "$status" -eq 0 ]
    assert_output_contains "already installed"
}

# ── Clean filter (binary working tree → canonical XML in index) ──

@test "clean filter fires on git add and stores canonical XML in the index" {
    configure_plist_filter
    write_binary_plist "$DOTFILES_ROOT/com.test.app.plist" "$SHUFFLED_PLIST_XML"

    git -C "$DOTFILES_ROOT" add com.test.app.plist
    [ "$?" -eq 0 ]

    # Index entry should be XML, not binary.
    run git -C "$DOTFILES_ROOT" show :com.test.app.plist
    [ "$status" -eq 0 ]
    assert_output_contains '<?xml version="1.0"'
    assert_output_contains '<key>apple</key>'
    assert_output_contains '<key>zebra</key>'

    # Keys must be alphabetised (clean filter sorts them).
    local apple_pos zebra_pos
    apple_pos=$(echo "$output" | grep -n "<key>apple</key>" | head -1 | cut -d: -f1)
    zebra_pos=$(echo "$output" | grep -n "<key>zebra</key>" | head -1 | cut -d: -f1)
    [ "$apple_pos" -lt "$zebra_pos" ]
}

@test "clean filter output is byte-stable across two `git add` invocations" {
    configure_plist_filter
    write_binary_plist "$DOTFILES_ROOT/foo.plist" "$SHUFFLED_PLIST_XML"

    git -C "$DOTFILES_ROOT" add foo.plist
    local first_blob
    first_blob="$(git -C "$DOTFILES_ROOT" rev-parse :foo.plist)"

    # Touch the file (different mtime, identical bytes) and re-add.
    # Stable XML output means git stores the same blob (same SHA).
    touch "$DOTFILES_ROOT/foo.plist"
    git -C "$DOTFILES_ROOT" add foo.plist
    local second_blob
    second_blob="$(git -C "$DOTFILES_ROOT" rev-parse :foo.plist)"

    [ "$first_blob" = "$second_blob" ]
}

# ── Smudge filter (XML in index → binary in working tree) ────────

@test "smudge filter fires on git checkout and produces a binary plist" {
    configure_plist_filter
    write_binary_plist "$DOTFILES_ROOT/foo.plist" "$SHUFFLED_PLIST_XML"
    git -C "$DOTFILES_ROOT" add foo.plist
    git -C "$DOTFILES_ROOT" commit -q -m "initial"

    # Wipe the working-tree file and ask git to restore it. The smudge
    # filter must fire and produce a binary plist.
    rm "$DOTFILES_ROOT/foo.plist"
    git -C "$DOTFILES_ROOT" checkout -- foo.plist

    # `bplist00` is the binary plist magic header — proves the smudge
    # filter actually ran (a no-op identity filter would emit XML).
    run head -c 8 "$DOTFILES_ROOT/foo.plist"
    [ "$status" -eq 0 ]
    [[ "$output" == bplist00* ]]
}

@test "round-trip: smudge then clean reproduces the same indexed blob" {
    configure_plist_filter
    write_binary_plist "$DOTFILES_ROOT/foo.plist" "$SHUFFLED_PLIST_XML"
    git -C "$DOTFILES_ROOT" add foo.plist
    git -C "$DOTFILES_ROOT" commit -q -m "initial"
    local blob_before
    blob_before="$(git -C "$DOTFILES_ROOT" rev-parse HEAD:foo.plist)"

    rm "$DOTFILES_ROOT/foo.plist"
    git -C "$DOTFILES_ROOT" checkout -- foo.plist
    git -C "$DOTFILES_ROOT" add foo.plist
    local blob_after
    blob_after="$(git -C "$DOTFILES_ROOT" rev-parse :foo.plist)"

    [ "$blob_before" = "$blob_after" ]
}

# ── Determinism: shuffled binaries stage to the SAME XML ─────────

@test "two semantically-equal binaries with shuffled keys stage to the same blob" {
    configure_plist_filter

    # Same logical plist — two writes produce two binary files with
    # potentially-different encoder layouts (the encoder may shuffle
    # top-level keys). The clean filter must canonicalize so the
    # indexed blob is identical.
    write_binary_plist "$DOTFILES_ROOT/a.plist" "$SHUFFLED_PLIST_XML"
    write_binary_plist "$DOTFILES_ROOT/b.plist" "$SHUFFLED_PLIST_XML"

    git -C "$DOTFILES_ROOT" add a.plist b.plist
    local blob_a blob_b
    blob_a="$(git -C "$DOTFILES_ROOT" rev-parse :a.plist)"
    blob_b="$(git -C "$DOTFILES_ROOT" rev-parse :b.plist)"

    [ "$blob_a" = "$blob_b" ]
}

# ── required = true makes corrupt input a hard failure ───────────

@test "required filter rejects corrupt input with a non-zero exit and actionable message" {
    configure_plist_filter
    # Garbage bytes that aren't a plist in any form.
    printf '\x00\x01\x02not a plist' > "$DOTFILES_ROOT/broken.plist"

    run git -C "$DOTFILES_ROOT" add broken.plist
    [ "$status" -ne 0 ]
    # Our error message must surface — git relays filter stderr.
    assert_output_contains "does not look like a valid plist"
    assert_output_contains "git-show-filters"
}

# ── gitattributes binding is filename-scoped ─────────────────────

@test "filter does NOT fire on non-plist files when gitattributes binds only *.plist" {
    configure_plist_filter

    # A file without the .plist extension — must skip the filter even
    # though it contains random bytes that are NOT a valid plist.
    printf 'just some text\n' > "$DOTFILES_ROOT/notes.txt"

    git -C "$DOTFILES_ROOT" add notes.txt
    run git -C "$DOTFILES_ROOT" show :notes.txt
    [ "$status" -eq 0 ]
    [ "$output" = "just some text" ]
}

# ── adopt + filter compose end-to-end ────────────────────────────

@test "adopt + git-install-filters: committing produces canonical XML in git" {
    if [[ "$(uname)" != "Darwin" ]]; then
        skip "Library/Preferences adopt path is macOS-only"
    fi

    # Stage a binary plist at the deployed location.
    mkdir -p "$HOME/Library/Preferences"
    write_binary_plist "$HOME/Library/Preferences/com.test.app.plist" "$SHUFFLED_PLIST_XML"

    create_pack "mac-defaults"
    run dodot adopt --into mac-defaults "$HOME/Library/Preferences/com.test.app.plist"
    [ "$status" -eq 0 ]

    # adopt should have placed the file under _lib/Preferences/.
    assert_exists "$DOTFILES_ROOT/mac-defaults/_lib/Preferences/com.test.app.plist"
    # And printed the install-filters tip (filters not yet registered).
    assert_output_contains "git-install-filters"

    # Now register filters AND wire .gitattributes (install-filters
    # only writes .git/config — the .gitattributes line travels with
    # the repo and is the user's to commit). Then commit; the
    # committed object must be canonical XML, not the binary that's
    # in the working tree.
    dodot git-install-filters
    echo '*.plist filter=dodot-plist' > "$DOTFILES_ROOT/.gitattributes"
    git -C "$DOTFILES_ROOT" add .gitattributes mac-defaults/
    git -C "$DOTFILES_ROOT" commit -q -m "adopt iina"

    run git -C "$DOTFILES_ROOT" show "HEAD:mac-defaults/_lib/Preferences/com.test.app.plist"
    [ "$status" -eq 0 ]
    assert_output_contains '<?xml version='
    assert_output_contains '<key>apple</key>'
}

# ── prompts registry persistence ─────────────────────────────────

@test "prompts list shows known prompts as active by default" {
    run dodot prompts list
    [ "$status" -eq 0 ]
    assert_output_contains "plist.install_filters"
    assert_output_contains "active"
}

@test "prompts reset --all is idempotent on an empty registry" {
    # Running reset --all when nothing is dismissed should not error.
    run dodot prompts reset --all
    [ "$status" -eq 0 ]
    assert_output_contains "No dismissed prompts"
}

@test "prompts reset rejects bare invocation with no key and no --all" {
    run dodot prompts reset
    [ "$status" -ne 0 ]
    assert_output_contains "requires either a key or --all"
}

@test "prompts reset rejects --all combined with a positional key" {
    run dodot prompts reset plist.install_filters --all
    [ "$status" -ne 0 ]
    assert_output_contains "not both"
}

# ── Filter does not fire when not registered ─────────────────────

@test "without filter registration, .gitattributes alone is inert (identity)" {
    # The repo has the binding in .gitattributes but no .git/config
    # entries — git falls back to the identity filter, so the binary
    # bytes go straight into the index.
    echo '*.plist filter=dodot-plist' > "$DOTFILES_ROOT/.gitattributes"
    write_binary_plist "$DOTFILES_ROOT/foo.plist" "$SHUFFLED_PLIST_XML"

    git -C "$DOTFILES_ROOT" add foo.plist
    run git -C "$DOTFILES_ROOT" show :foo.plist
    [ "$status" -eq 0 ]
    # First eight bytes of binary plists are `bplist00` — no XML.
    [[ "${output:0:8}" == bplist00* ]]
}
