# SSH configuration pack
name = "ssh"

# Create .ssh directory and link config
[[matchers]]
triggers = [
    { type = "FileName", pattern = "config" }
]
actions = [
    { type = "Symlink", target = ".ssh/config" }
]