version: 2

project_name: dodot

builds:
  - id: dodot
    main: ./cmd/dodot/main
    binary: dodot
    ldflags:
      - -s -w -X github.com/arthur-debert/dodot/internal/version.Version={{.Version}} -X github.com/arthur-debert/dodot/internal/version.Commit={{.Commit}} -X github.com/arthur-debert/dodot/internal/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64

before:
  hooks:
    # Generate completions and man pages (goreleaser will build the binary)
    - ./scripts/gen-completion
    - ./scripts/gen-manpage

archives:
  - id: dodot-archive
    ids: [dodot]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "dodot-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "README.md"
      - "LICENSE"
      - src: "dist/build/completions/*"
        dst: "completions"
      - src: "dist/build/man/man1/*"
        dst: "man/man1"
      - src: "pkg/shell/*"
        dst: "shell"
      - src: "pkg/ui/output/styles/styles.yaml"
        dst: "styles/styles.yaml"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

brews:
  - ids: [dodot-archive]
    name: dodot
    repository:
      owner: arthur-debert
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    # Fixed: Always use Formula directory (the debug conditional was causing issues)
    directory: Formula
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/arthur-debert/dodot"
    description: "Description of your CLI tool"
    license: "MIT"
    test: |
      system "#{bin}/dodot --help"
    install: |
      bin.install "dodot"
      
      # Install shell completions
      bash_completion.install "completions/dodot.bash" if File.exist?("completions/dodot.bash")
      zsh_completion.install "completions/_dodot" if File.exist?("completions/_dodot")
      fish_completion.install "completions/dodot.fish" if File.exist?("completions/dodot.fish")
      
      # Install man page
      man1.install "man/man1/dodot.1.gz" if File.exist?("man/man1/dodot.1.gz")
      
      # Install shell integration scripts
      pkgshare.install "shell" if Dir.exist?("shell")
      
      # Install styles configuration
      pkgshare.install "styles" if Dir.exist?("styles")

# nFPM packages (deb, rpm, etc.)
# https://goreleaser.com/customization/nfpm/
nfpms:
  - id: dodot
    builds: [dodot]
    formats: [deb, rpm, apk]
    package_name: dodot
    file_name_template: "dodot_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: "https://github.com/arthur-debert/dodot"
    maintainer: "Arthur Debert <arthur@debert.xyz>"
    description: "Description of your CLI tool"
    license: "MIT"
    section: utils
    priority: optional
    contents:
      # Man page
      - src: man/man1/dodot.1.gz
        dst: /usr/share/man/man1/dodot.1.gz
        file_info:
          mode: 0644
      # Bash completion
      - src: completions/dodot.bash
        dst: /usr/share/bash-completion/completions/dodot
        file_info:
          mode: 0644
      # Zsh completion
      - src: completions/_dodot
        dst: /usr/share/zsh/site-functions/_dodot
        file_info:
          mode: 0644
      # Fish completion
      - src: completions/dodot.fish
        dst: /usr/share/fish/vendor_completions.d/dodot.fish
        file_info:
          mode: 0644
      # Shell integration scripts
      - src: shell/dodot-init.sh
        dst: /usr/share/dodot/shell/dodot-init.sh
        file_info:
          mode: 0755
      - src: shell/dodot-init.fish
        dst: /usr/share/dodot/shell/dodot-init.fish
        file_info:
          mode: 0755
      # Styles configuration
      - src: styles/styles.yaml
        dst: /usr/share/dodot/styles/styles.yaml
        file_info:
          mode: 0644

env:
  - PKG_NAME={{ .Env.PKG_NAME }}
