:: verified ::
Shell integration

    dodot deploys in two layers, and they fail independently. `dodot up` materializes your packs into the datastore: it proves symlinks point at sources, Brewfiles ran, the init script was regenerated. *Shells activate that state* by sourcing the generated init script — and nothing about a green `up` says any shell ever will.

    Two of dodot's handlers only matter at shell startup: `shell` stages files to be sourced into your interactive shell, and `path` stages directories to be prepended to `$PATH`. Neither does anything until a shell loads dodot's init script. Wiring that up is a one-time step, and dodot owns it:

        dodot install --write

    :: shell ::

    That writes one marked block to your shell's startup file, then starts a shell to check that the block actually fires — so the step ends on a measurement rather than an assumption. Run it bare first (`dodot install`) if you want to see the decision before delegating it; without `--write` nothing is written.

    You can also wire it by hand with `eval "$(dodot init-sh)"` — see [#7]. That path is fully supported and existing hookups keep working untouched; it is just no longer the one you have to do yourself.

    This doc is the story of where the hookup goes, what it does, how to tell whether it is working, and what shouldn't surround it.

    :: note :: Terminology — this doc uses [pack] and [handler]. See [./glossary/] if unfamiliar.

1. When you reach for this doc

    - Setting up dodot on a new machine: you need the hookup in your rc.
    - Your shell aliases or PATH additions from a pack aren't taking effect.
    - `dodot up` or `dodot status` said no shell has loaded dodot yet, and you want to know what that means.
    - You're diagnosing slow shell startup or a broken init.
    - You're wondering what the hookup actually does and why it's safe.

2. Wiring it up

    From anywhere, after installing dodot:

        $ dodot install --write

        verifying shell integration (zsh)…
        Wired dodot into ~/.zshrc (created).

        Shell
          zsh
        Startup file
          ~/.zshrc
        Hook
          present (dodot's managed block)
          [ -f "$HOME/.local/share/dodot/shell/dodot-init.sh" ] && . "$HOME/.local/share/dodot/shell/dodot-init.sh"
        Notes
          created ~/.zshrc

        ✓ Shell hookup: dodot is sourced in new shells.
        Last loaded just now by dodot 5.6.0.

    :: shell ::

    What went into the file is one marked block, and nothing else:

        # >>> dodot shell hookup >>>
        [ -f "$HOME/.local/share/dodot/shell/dodot-init.sh" ] && . "$HOME/.local/share/dodot/shell/dodot-init.sh"
        # <<< dodot shell hookup <<<

    :: shell ::

    Re-running is safe: an existing block is replaced in place, never duplicated. Deleting the block is a complete uninstall of the hookup. The command picks the file (zsh → `${ZDOTDIR:-$HOME}/.zshrc`, bash → `~/.bashrc` plus the macOS login-shell chain, symlinks written through to your dotfiles repo, `--rc` to override); [./commands/install.lex] §4 has the full ladder.

    Once per machine. The init script itself is regenerated by every `dodot up` and `dodot down`, so adding new packs surfaces in your next shell automatically — you never touch the rc block again.

3. What the init script contains

    A flat shell script: one `source <path>` line per shell-handler source, one `export PATH="<dir>:$PATH"` line per path-handler source, with a `# [<pack>]` comment above each so you can tell what came from where.

    On a macOS host with Homebrew installed, the script *opens* with Homebrew's environment — `brew shellenv` output captured verbatim at the last `dodot up` and cached in the datastore — so brew's `$PATH` entries exist before any pack script runs and your rc needs no bootstrap line of its own. It is emitted first so that dodot's own PATH additions below it win. This block is the one command dodot puts on the shell startup path; [./configuration.lex] §10 documents what it costs, how the capture is cached, and the `[shell] homebrew = "auto" | "off"` key that controls it.

    No logic at runtime, no datastore re-discovery. Every line is computed at `dodot up` time, when the script is regenerated. Sourcing the script is just running those plain shell commands — same as if you'd written them by hand.

    Inspect it:

        dodot init-sh
        dodot init-sh | less

    :: shell ::

    A pack with no shell or path handlers contributes nothing. A pack you took down with `dodot down` disappears from the regenerated script entirely. On a fresh install with no packs deployed yet, the script is a header plus a "no shell scripts or PATH additions to load" comment — sourcing it is harmless and just doesn't do anything.

    The script also leaves *evidence* that it ran: it exports a generation stamp and touches a heartbeat file in dodot's data directory. That is what makes the states in [#5] measurable rather than guessed. The cost is one export and one redirect per shell start; no dodot process runs on the hot path.

4. Which file it goes in, and why

    The hookup belongs in whichever shell rc your *interactive* shells read on every session:

        | Shell | File         |
        | bash  | `~/.bashrc`  |
        | zsh   | `~/.zshrc`   |
    :: table align=ll ::

    Per-session, not login-only. `~/.profile` runs once per login; `~/.bashrc` and `~/.zshrc` run per shell. New terminal windows from a windowed session re-read the per-session file but not the login file — putting the hookup in the wrong one means new terminals don't pick up changes between logins.

    macOS bash is the exception that proves it: Terminal opens *login* shells, which read `~/.bash_profile` and never `~/.bashrc`. `dodot install --write` handles this by chaining the profile to `.bashrc` when nothing there does already. Wiring by hand, you have to remember it.

5. Activation states

    Because the init script leaves evidence, `dodot up`, `dodot down`, and `dodot status` end with a *footer* about activation instead of assuming shells load dodot. Line one says whether dodot is sourced in new shell sessions, colour-coded by severity; when something needs doing, a hint follows. The last line, dimmed, is the evidence:

        Last loaded 4 minutes ago by dodot 5.6.0.

    :: text ::

    "Last loaded" is the heartbeat file's modification time — when a shell last actually sourced the init script, which is not the same as when `dodot up` generated it. The version is the dodot that generated the script that shell loaded. Evidence left by a dodot old enough to carry no version renders as `≤5.5.1` — the last release before the evidence learned to identify itself. When no shell has ever loaded dodot, the line reads `Never loaded.`; when the heartbeat's timestamp is unreadable, `Last loaded at an unknown time by dodot <version>.`

    Two things can be true at once here, and the line says so rather than blending them. dodot has two signals: the shell you are typing in reports which dodot *it* loaded, and the heartbeat reports when *some* shell last loaded one. Usually they name the same dodot and there is one sentence. When they disagree — mid-upgrade, most often — the time belongs to the heartbeat's activation and not to your shell's, so the line reports both events instead of pairing one's timestamp with the other's version:

        This shell loaded dodot 5.6.0; the last shell to load ran dodot 5.0.0, 4 minutes ago.

    :: shell ::

    One case has no footer at all: before a first deploy there is no init script on disk, so there is no hookup to have. `dodot status` on a machine where `dodot up` has never run says nothing about activation — and neither does a `dodot up --dry-run` there, which regenerates nothing. A real `up` writes the script before it reports, so it always ends on a footer.

    This section is where every state and its exact message live; other pages link here rather than repeating them. There are seven states, and seven different things to do.

    Activation states — line one, quoted verbatim:
        | State            | Line one                                                                | What to do                                     |
        | healthy          | Shell hookup: dodot is sourced in new shells.                           | Nothing.                                       |
        | version skew     | Shell hookup: your shells load a different dodot.                       | Find which install your PATH resolves first — see below. |
        | empty script     | Shell hookup: wired, but no packs are deployed. | `dodot up` — expected right after `dodot down`. |
        | stale shell      | Shell hookup: this shell predates your last \`dodot up\`.               | Open a new shell.                              |
        | shell not loaded | Shell hookup: this shell did not load dodot.                            | What the hint names: the hook is missing from your rc (wire it), or it's there and this is likely an old shell (open a new one). |
        | never activated  | Shell hookup: no shell has loaded dodot yet.                            | `dodot install --write`.                       |
        | verified broken  | Shell hookup: a new shell did not load dodot.                           | Fix what the diagnosis names — see below.      |

    :: table align=lll ::

    _Healthy_ — a shell has loaded the current init script, generated by the dodot you are running:

        ✓ Shell hookup: dodot is sourced in new shells.
        Last loaded 4 minutes ago by dodot 5.6.0.

    :: shell ::

    _Version skew_ — the evidence was left by a *different* dodot than the one you are running. This is the wired-but-dead hookup's most likely cause: an old install earlier on `$PATH` is what your shells actually execute, and no amount of opening new shells will change it. It is a warning, not an error — mid-upgrade it appears transiently and the next shell clears it:

        ⚠ Shell hookup: your shells load a different dodot.
        Open a new shell. If that changes nothing, the `dodot` your shells run is a different install than the one you just ran — check which one your PATH finds first.
        Last loaded 4 minutes ago by dodot 5.0.0 — you are running 5.6.0.

    :: shell ::

    This state is not only inferred. When `dodot up` or `dodot install --write` starts a shell to check the hookup (see _Verified broken_ below), that shell reports both halves of what it loaded — the generation *and* the dodot that wrote it — so a hookup that mints a perfectly current generation from the wrong binary is measured as skew rather than certified as healthy. That is the failure this whole page exists for, and it is exactly the case a generation alone reads as fine.

    For the measured answer — which binary `dodot` resolves to at the hook line, and why — run `dodot probe shell-init` ([./commands/probe.lex] §4).

    _Empty script_ — the hookup is wired and firing, but the generated script carries no pack contributions, so a healthy-sounding line would be misleading. This is what `dodot down` leaves behind, and also a first `up` that deployed nothing. The line says "no packs", not "the script is empty": on a Homebrew host the script still carries the `brew shellenv` block ([#3]) and is doing real work — just none of yours. It reads the same whether dodot inferred the hookup was firing or measured it:

        Shell hookup: wired, but no packs are deployed.
        Run `dodot up` to deploy your packs.
        Last loaded just now by dodot 5.6.0.

    :: shell ::

    _Stale shell_ — *this* shell loaded dodot, but before your last `dodot up`:

        Shell hookup: this shell predates your last `dodot up`.
        Open a new shell to pick up the current deployment.
        Last loaded 4 minutes ago by dodot 5.6.0.

    :: shell ::

    _Shell not loaded_ comes from any command running attached to a terminal that did not start a shell to check: no matter what the heartbeat says some past shell did, the shell you are typing in exported no generation stamp, so it demonstrably did not load dodot. That is `dodot status` always, and `dodot up` whenever the cheap evidence was conclusive enough that it never spawned anything — most often *because* the heartbeat is fresh, which is the exact reading this state exists to overrule. The two agree, deliberately: a hookup that has quietly died gets the same answer whichever command you happen to run. This is how dodot catches a hookup that *used to* work and then broke — an rc rewrite, a commented-out hook, a moved dotfiles repo — without starting a shell. A scan of your rc file picks the hint. Hook missing:

        ⚠ Shell hookup: this shell did not load dodot.
        ~/.zshrc doesn't have the dodot hook. Run `dodot install --write` to wire it up, or add this line yourself: [ -f "$HOME/.local/share/dodot/shell/dodot-init.sh" ] && . "$HOME/.local/share/dodot/shell/dodot-init.sh"
        Last loaded 2 days ago by dodot 5.6.0.

    :: shell ::

    …or hook present, in which case this is most likely a shell opened before the hook landed:

        Shell hookup: this shell did not load dodot.
        The hook is in ~/.zshrc, so this shell probably predates it — open a new shell. If that changes nothing, run `dodot up` to diagnose.
        Last loaded 2 days ago by dodot 5.6.0.

    :: shell ::

    The wording stays "this shell", not "your hookup is broken", on purpose: an editor's task shell legitimately reads no rc file, and dodot can't tell that apart from a broken hookup without measuring. When dodot runs with no terminal at all (cron, scripts), this state never fires — a fresh heartbeat still reads as healthy there.

    _Never activated_ — no shell has ever loaded dodot's init script; there is no heartbeat at all:

        ⚠ Shell hookup: no shell has loaded dodot yet.
        Run `dodot install --write` to wire it up, or add this to your shell rc file yourself: [ -f "$HOME/.local/share/dodot/shell/dodot-init.sh" ] && . "$HOME/.local/share/dodot/shell/dodot-init.sh"
        Never loaded.

    :: shell ::

    _Verified broken_ comes only from `dodot up` or `dodot install --write`, which are the two commands allowed to start a shell to find out. The diagnosis splits, because the cases need different fixes — the hook is missing from the file:

        ✗ Shell hookup: a new shell did not load dodot.
        The dodot hook is missing from ~/.zshrc — run `dodot install --write` to add it.
        Never loaded.

    :: shell ::

    …or the hook is there but nothing reaches it:

        ✗ Shell hookup: a new shell did not load dodot.
        The dodot hook is in ~/.zshrc but was never reached — something earlier in that file is failing before it.
        Last loaded 9 days ago by dodot ≤5.5.1.

    :: shell ::

    That second one is the case a static scan of your rc would report as fine. It is why dodot measures. (Two rarer diagnoses exist: the shell sourced an *older* init script — check for a second dodot hook or a stale copy — and the shell whose rc file dodot cannot name, where the hint carries the line to paste.)

    Who starts a shell, and when:

    - `dodot status` never does. It reports the evidence it can read for free, so it stays safe to run anywhere.
    - `dodot up` does, but only when the cheap evidence is inconclusive — no current stamp *and* no fresh heartbeat. That is the fresh-install case and the broken-hook case. The first real shell activation writes the heartbeat and the check retires; a healthy machine never pays for it.
    - `dodot install --write` does, unconditionally, because you just asked it to change the file and a measured answer is what makes the change worth trusting.

    The spawn is announced when it happens (`verifying shell integration (zsh)…`), runs your shell interactive but non-login with stdin from `/dev/null`, and is killed on a hard timeout. A timeout or a spawn failure degrades to reporting what is *configured*, clearly labelled as such — it never wedges `up`.

6. What goes above and below the dodot line

    One narrow category belongs *above* the dodot block (or your manual eval):

    - *OS-level prereqs that block any pack from succeeding.* xcode-select install prompts, license acceptance — anything that has to be in place before any handler can run.

    Homebrew used to be the other one, and no longer is: the init script itself now opens with brew's environment ([#3]), so nothing brew-related needs to sit in your rc. One exception survives, and only for the hand-wired form: `eval "$(dodot init-sh)"` has to *find* `dodot` before the init script can run, so if Homebrew is what installed dodot, `eval "$(/opt/homebrew/bin/brew shellenv)"` still has to come before your eval line. The managed block sources a file by absolute path and has no such need — that bootstrap cycle is one of the reasons it is the recommended form ([#7]).

    *Below*, ideally nothing. If you have shell logic that depends on something dodot stages (an alias, a helper function, an environment variable), put it in the same pack so the ordering is internal to the generated script rather than scattered across your rc.

    Everything else — aliases, exports, functions, completions, prompt setup, fzf/nvm/asdf integration, et cetera — belongs in a pack. The point of dodot is that the rc stays minimal; if you find yourself adding lines around the dodot block, ask whether they could live in a pack instead.

    The exception: shell-specific tooling that ships its own init line and refuses to be moved. A few such cases exist; everything else should be moving in toward a pack.

7. Wiring it by hand

    The manual alternative, unchanged and fully supported:

        eval "$(dodot init-sh)"

    :: shell ::

    Same rules as [#4] — a per-session rc, once per machine. Existing hookups of this shape keep working exactly as they did; the evidence in [#3] rides inside the emitted script either way, so the states in [#5] work for a hand-wired hookup too. There is no migration to do.

    Reasons to prefer the managed block anyway:

    - It sources the generated file directly instead of invoking dodot, so no process runs on every shell start.
    - It has no bootstrap problem. `eval "$(dodot init-sh)"` needs `dodot` on `$PATH` already — which fails when the `$PATH` entry that finds dodot is one dodot's own init provides.
    - Its `[ -f … ]` guard makes a missing or reset datastore a silent no-op instead of a startup error.
    - `dodot install` can verify it, name the file it lives in, and repoint it when your data directory moves.

    Reasons to wire by hand anyway: you keep your rc under your own tooling and want no managed blocks in it, or your shell isn't one dodot writes for (see [./commands/install.lex] §7).

    If you already have the eval line, `dodot install` reports it as `present (wired by hand — dodot leaves it alone)` and does not claim it. Don't run `--write` on top of it unless you remove your line first — otherwise the init script gets sourced twice.

8. Inspecting and diagnosing

    Is the hookup working?

        dodot status

    :: shell ::

    Where does the hook live, and is it there?

        dodot install

    :: shell ::

    What would a new shell source?

        dodot init-sh

    :: shell ::

    What does `dodot` resolve to at the hook line — plus per-source timings and errors from your last shell start:

        dodot probe shell-init

    :: shell ::

    That is the deep diagnosis for a hookup the footer flags as skewed or dead: it runs your rc under tracing and names the rc file, the hook's line, and which binary `dodot` resolves to *at that line* — including stale installs it passed over on the way. See [./commands/probe.lex] §4.

    The probe surfaces stale data with a flag if the report predates the most recent `dodot up` — staleness is detected via `$XDG_DATA_HOME/dodot/last-up-at` (typically `~/.local/share/dodot/last-up-at`), written on every successful `up`.

9. Watch out for

    - *Wire it once.* Putting the hookup in both `~/.bashrc` and `~/.bash_profile` (or in two layers of rc include, or as both a managed block and a manual eval) duplicates every `source` and `export PATH=` line in the resulting environment. Usually harmless; sometimes it re-triggers one-time setup snippets you wrote in your aliases.
    - *Open shells lag.* `dodot up` regenerates the script; already-running shells still hold their old environment. That is exactly what the _stale shell_ state reports. Source the rc again or open a new shell.
    - *Failures are loud, not silent.* If a sourced script errors, the generated init prints `dodot: shell source exited <code>: <path>` to stderr — failures are not swallowed. Silently broken shell init is worse than a visible error.
    - *Shell-specific files require matching shells.* `*.zsh` files only parse cleanly under zsh; `*.bash` only under bash. `*.sh` is the portable bucket. A zsh-only file in a pack will surface as a visible source error in a bash shell.
    - *Recursion is depth-1.* Pack scanning is depth-1, so a nested `nested/scripts/foo.sh` is *not* picked up by the shell handler — it falls through to the symlink handler. That keeps window-manager helper scripts and similar nested `.sh` files from being auto-sourced.

10. Live edits

    Editing a file under symlink management is live (see [./paths.lex] §7). For a file the *shell* handler sources, the edit takes effect on the next shell start — the file is sourced once at startup, and the staging path *is* your edit via the symlink chain. The path handler's prepended `$PATH` entry is also activated on the next shell start; the directory contents themselves are live (drop in a new executable and it's available immediately to any shell that already has the directory on `$PATH`).

    `dodot up` regenerates the init script every run, so adding or removing a pack with shell/path handlers refreshes which sources are wired in — but again, only on next shell start.

    The rc hookup itself is not live in either direction: adding the block affects shells started after it, and dodot never rewrites the block behind your back. Re-run `dodot install --write` when you want it repointed.

11. See also

    - [./commands/install.lex] — the command that owns the rc block, in detail.
    - [./commands/init-sh.lex] — the script the hookup sources.
    - [./handlers/shell.lex], [./handlers/path.lex] — the two handlers this script wires up.
    - [./commands/probe.lex] — diagnostics for the shell-init layer.
    - [./getting-started.lex] §6 — where the hookup first appears in the broader onboarding flow.
    - [./glossary/handler.lex].
