:: verified ::
Shell integration

    dodot deploys in two layers, and they fail independently. `dodot up` materializes your packs into the datastore: it proves symlinks point at sources, Brewfiles ran, the init script was regenerated. *Shells activate that state* by sourcing the generated init script — and nothing about a green `up` says any shell ever will.

    Two of dodot's handlers only matter at shell startup: `shell` stages files to be sourced into your interactive shell, and `path` stages directories to be prepended to `$PATH`. Neither does anything until a shell loads dodot's init script. Wiring that up is a one-time step, and dodot owns it:

        dodot install --write

    :: shell ::

    That writes one marked block to your shell's startup file, then starts a shell to check that the block actually fires — so the step ends on a measurement rather than an assumption. Run it bare first (`dodot install`) if you want to see the decision before delegating it; without `--write` nothing is written.

    You can also wire it by hand with `eval "$(dodot init-sh)"` — see [#7]. That path is fully supported and existing hookups keep working untouched; it is just no longer the one you have to do yourself.

    This doc is the story of where the hookup goes, what it does, how to tell whether it is working, and what shouldn't surround it.

    :: note :: Terminology — this doc uses [pack] and [handler]. See [./glossary/] if unfamiliar.

1. When you reach for this doc

    - Setting up dodot on a new machine: you need the hookup in your rc.
    - Your shell aliases or PATH additions from a pack aren't taking effect.
    - `dodot up` or `dodot status` said no shell has loaded dodot yet, and you want to know what that means.
    - You're diagnosing slow shell startup or a broken init.
    - You're wondering what the hookup actually does and why it's safe.

2. Wiring it up

    From anywhere, after installing dodot:

        $ dodot install --write

        verifying shell integration (zsh)…
        Wired dodot into ~/.zshrc (created).

        Shell
          zsh
        Startup file
          ~/.zshrc
        Hook
          present (dodot's managed block)
          [ -f "$HOME/.local/share/dodot/shell/dodot-init.sh" ] && . "$HOME/.local/share/dodot/shell/dodot-init.sh"
        Notes
          created ~/.zshrc

        ✓ Shell hookup verified: a new shell loads dodot.

    :: shell ::

    What went into the file is one marked block, and nothing else:

        # >>> dodot shell hookup >>>
        [ -f "$HOME/.local/share/dodot/shell/dodot-init.sh" ] && . "$HOME/.local/share/dodot/shell/dodot-init.sh"
        # <<< dodot shell hookup <<<

    :: shell ::

    Re-running is safe: an existing block is replaced in place, never duplicated. Deleting the block is a complete uninstall of the hookup. The command picks the file (zsh → `${ZDOTDIR:-$HOME}/.zshrc`, bash → `~/.bashrc` plus the macOS login-shell chain, symlinks written through to your dotfiles repo, `--rc` to override); [./commands/install.lex] §4 has the full ladder.

    Once per machine. The init script itself is regenerated by every `dodot up` and `dodot down`, so adding new packs surfaces in your next shell automatically — you never touch the rc block again.

3. What the init script contains

    A flat shell script: one `source <path>` line per shell-handler source, one `export PATH="<dir>:$PATH"` line per path-handler source, with a `# [<pack>]` comment above each so you can tell what came from where.

    No logic at runtime, no datastore re-discovery. Every line is computed at `dodot up` time, when the script is regenerated. Sourcing the script is just running those plain shell commands — same as if you'd written them by hand.

    Inspect it:

        dodot init-sh
        dodot init-sh | less

    :: shell ::

    A pack with no shell or path handlers contributes nothing. A pack you took down with `dodot down` disappears from the regenerated script entirely. On a fresh install with no packs deployed yet, the script is a header plus a "no shell scripts or PATH additions to load" comment — sourcing it is harmless and just doesn't do anything.

    The script also leaves *evidence* that it ran: it exports a generation stamp and touches a heartbeat file in dodot's data directory. That is what makes the states in [#5] measurable rather than guessed. The cost is one export and one redirect per shell start; no dodot process runs on the hot path.

4. Which file it goes in, and why

    The hookup belongs in whichever shell rc your *interactive* shells read on every session:

        | Shell | File         |
        | bash  | `~/.bashrc`  |
        | zsh   | `~/.zshrc`   |
    :: table align=ll ::

    Per-session, not login-only. `~/.profile` runs once per login; `~/.bashrc` and `~/.zshrc` run per shell. New terminal windows from a windowed session re-read the per-session file but not the login file — putting the hookup in the wrong one means new terminals don't pick up changes between logins.

    macOS bash is the exception that proves it: Terminal opens *login* shells, which read `~/.bash_profile` and never `~/.bashrc`. `dodot install --write` handles this by chaining the profile to `.bashrc` when nothing there does already. Wiring by hand, you have to remember it.

5. Activation states

    Because the init script leaves evidence, `dodot up` and `dodot status` can tell you whether shells are actually loading dodot instead of assuming it. Four states, four different things to do:

    Activation states:
        | State           | What it means                                                    | What to do                                     |
        | healthy         | A shell has loaded the current init script.                      | Nothing. `status` shows a quiet `shell hookup: ok`. |
        | stale shell     | *This* shell loaded dodot, but before your last `dodot up`.      | Open a new shell.                              |
        | never activated | No shell has ever loaded dodot's init script.                    | `dodot install --write`.                       |
        | verified broken | dodot started a shell and measured that it did not load dodot.   | Fix what the diagnosis names — see below.      |

    :: table align=lll ::

    _Never activated_, from `dodot status` — evidence only, no shell is started:

        ⚠ Deployed, but no shell has loaded dodot yet.
        Run `dodot install --write` to wire it up, or add this to your shell rc file yourself: [ -f "$HOME/.local/share/dodot/shell/dodot-init.sh" ] && . "$HOME/.local/share/dodot/shell/dodot-init.sh"

    :: shell ::

    _Stale shell_:

        This shell started before your last `dodot up`.
        Open a new shell to pick up the current deployment.

    :: shell ::

    _Verified broken_ comes only from `dodot up` or `dodot install --write`, which are the two commands allowed to start a shell to find out. The diagnosis splits two ways, because they need different fixes — the hook is missing from the file:

        Deployed, but a new shell did not load dodot.
        The dodot hook is missing from ~/.zshrc — run `dodot install --write` to add it.

    :: shell ::

    …or the hook is there but nothing reaches it:

        Deployed, but a new shell did not load dodot.
        The dodot hook is in ~/.zshrc but was never reached — something earlier in that file is failing before it.

    :: shell ::

    That second one is the case a static scan of your rc would report as fine. It is why dodot measures.

    Who starts a shell, and when:

    - `dodot status` never does. It reports the evidence it can read for free, so it stays safe to run anywhere.
    - `dodot up` does, but only when the cheap evidence is inconclusive — no current stamp *and* no fresh heartbeat. That is the fresh-install case and the broken-hook case. The first real shell activation writes the heartbeat and the check retires; a healthy machine never pays for it.
    - `dodot install --write` does, unconditionally, because you just asked it to change the file and a measured answer is what makes the change worth trusting.

    The spawn is announced when it happens (`verifying shell integration (zsh)…`), runs your shell interactive but non-login with stdin from `/dev/null`, and is killed on a hard timeout. A timeout or a spawn failure degrades to reporting what is *configured*, clearly labelled as such — it never wedges `up`.

6. What goes above and below the dodot line

    Two narrow categories belong *above* the dodot block (or your manual eval):

    - *Homebrew shellenv.* Homebrew is what puts `dodot` itself on `$PATH`:

            eval "$(/opt/homebrew/bin/brew shellenv)"   # Apple Silicon
            eval "$(/usr/local/bin/brew shellenv)"      # Intel macOS

        :: shell ::

        The marked block needs this less than the manual eval does — it sources a file by absolute path rather than invoking dodot — but anything else in your rc that calls `dodot` still needs Homebrew first.

    - *OS-level prereqs that block any pack from succeeding.* xcode-select install prompts, license acceptance — anything that has to be in place before any handler can run.

    *Below*, ideally nothing. If you have shell logic that depends on something dodot stages (an alias, a helper function, an environment variable), put it in the same pack so the ordering is internal to the generated script rather than scattered across your rc.

    Everything else — aliases, exports, functions, completions, prompt setup, fzf/nvm/asdf integration, et cetera — belongs in a pack. The point of dodot is that the rc stays minimal; if you find yourself adding lines around the dodot block, ask whether they could live in a pack instead.

    The exception: shell-specific tooling that ships its own init line and refuses to be moved. A few such cases exist; everything else should be moving in toward a pack.

7. Wiring it by hand

    The manual alternative, unchanged and fully supported:

        eval "$(dodot init-sh)"

    :: shell ::

    Same rules as [#4] — a per-session rc, once per machine. Existing hookups of this shape keep working exactly as they did; the evidence in [#3] rides inside the emitted script either way, so the states in [#5] work for a hand-wired hookup too. There is no migration to do.

    Reasons to prefer the managed block anyway:

    - It sources the generated file directly instead of invoking dodot, so no process runs on every shell start.
    - It has no bootstrap problem. `eval "$(dodot init-sh)"` needs `dodot` on `$PATH` already — which fails when the `$PATH` entry that finds dodot is one dodot's own init provides.
    - Its `[ -f … ]` guard makes a missing or reset datastore a silent no-op instead of a startup error.
    - `dodot install` can verify it, name the file it lives in, and repoint it when your data directory moves.

    Reasons to wire by hand anyway: you keep your rc under your own tooling and want no managed blocks in it, or your shell isn't one dodot writes for (see [./commands/install.lex] §7).

    If you already have the eval line, `dodot install` reports it as `present (wired by hand — dodot leaves it alone)` and does not claim it. Don't run `--write` on top of it unless you remove your line first — otherwise the init script gets sourced twice.

8. Inspecting and diagnosing

    Is the hookup working?

        dodot status

    :: shell ::

    Where does the hook live, and is it there?

        dodot install

    :: shell ::

    What would a new shell source?

        dodot init-sh

    :: shell ::

    Per-source timings and errors from your last shell start:

        dodot probe shell-init

    :: shell ::

    The probe surfaces stale data with a flag if the report predates the most recent `dodot up` — staleness is detected via `$XDG_DATA_HOME/dodot/last-up-at` (typically `~/.local/share/dodot/last-up-at`), written on every successful `up`.

9. Watch out for

    - *Wire it once.* Putting the hookup in both `~/.bashrc` and `~/.bash_profile` (or in two layers of rc include, or as both a managed block and a manual eval) duplicates every `source` and `export PATH=` line in the resulting environment. Usually harmless; sometimes it re-triggers one-time setup snippets you wrote in your aliases.
    - *Open shells lag.* `dodot up` regenerates the script; already-running shells still hold their old environment. That is exactly what the _stale shell_ state reports. Source the rc again or open a new shell.
    - *Failures are loud, not silent.* If a sourced script errors, the generated init prints `dodot: shell source exited <code>: <path>` to stderr — failures are not swallowed. Silently broken shell init is worse than a visible error.
    - *Shell-specific files require matching shells.* `*.zsh` files only parse cleanly under zsh; `*.bash` only under bash. `*.sh` is the portable bucket. A zsh-only file in a pack will surface as a visible source error in a bash shell.
    - *Recursion is depth-1.* Pack scanning is depth-1, so a nested `nested/scripts/foo.sh` is *not* picked up by the shell handler — it falls through to the symlink handler. That keeps window-manager helper scripts and similar nested `.sh` files from being auto-sourced.

10. Live edits

    Editing a file under symlink management is live (see [./paths.lex] §7). For a file the *shell* handler sources, the edit takes effect on the next shell start — the file is sourced once at startup, and the staging path *is* your edit via the symlink chain. The path handler's prepended `$PATH` entry is also activated on the next shell start; the directory contents themselves are live (drop in a new executable and it's available immediately to any shell that already has the directory on `$PATH`).

    `dodot up` regenerates the init script every run, so adding or removing a pack with shell/path handlers refreshes which sources are wired in — but again, only on next shell start.

    The rc hookup itself is not live in either direction: adding the block affects shells started after it, and dodot never rewrites the block behind your back. Re-run `dodot install --write` when you want it repointed.

11. See also

    - [./commands/install.lex] — the command that owns the rc block, in detail.
    - [./commands/init-sh.lex] — the script the hookup sources.
    - [./handlers/shell.lex], [./handlers/path.lex] — the two handlers this script wires up.
    - [./commands/probe.lex] — diagnostics for the shell-init layer.
    - [./getting-started.lex] §6 — where the hookup first appears in the broader onboarding flow.
    - [./glossary/handler.lex].
