name = "bash"

# Deploy .bashrc as symlink
[[matchers]]
triggers = [
    { type = "FileName", pattern = ".bashrc" }
]
actions = [
    { type = "symlink" }
]

# Source aliases.sh for shell profile
[[matchers]]
triggers = [
    { type = "FileName", pattern = "aliases.sh" }
]
actions = [
    { type = "shell_profile" }
]