# Internal dodot system defaults
# These are embedded in the binary and provide the base configuration

logging:
  default_level: warn
  verbosity_levels:
    0: warn
    1: info
    2: debug
    3: trace
  time_format: "15:04"
  enable_color: true
  enable_caller_at_verbosity: 2

priorities:
  triggers:
    filename: 100
    directory: 90
    catchall: 0
  
  handlers:
    symlink: 100
    path: 90
    install: 90
    shell: 80
    homebrew: 90
    template: 70

shell_integration:
  bash_zsh_snippet: '[ -f "$HOME/.local/share/dodot/shell/dodot-init.sh" ] && source "$HOME/.local/share/dodot/shell/dodot-init.sh"'
  bash_zsh_snippet_with_custom: '[ -f "%s/shell/dodot-init.sh" ] && source "%s/shell/dodot-init.sh"'
  fish_snippet: |-
    if test -f "$HOME/.local/share/dodot/shell/dodot-init.fish"
        source "$HOME/.local/share/dodot/shell/dodot-init.fish"
    end

file_permissions:
  directory: 0755
  file: 0644
  executable: 0755

# Security configuration
security:
  protected_paths:
    .ssh/authorized_keys: true
    .ssh/id_rsa: true
    .ssh/id_ed25519: true
    .gnupg: true
    .password-store: true
    .config/gh/hosts.yml: true
    .aws/credentials: true
    .kube/config: true
    .docker/config.json: true

# Link path configuration - these always go to $HOME
link_paths:
  force_home:
    ssh: true
    gnupg: true
    aws: true
    kube: true
    docker: true
    gitconfig: true
    bashrc: true
    zshrc: true
    profile: true

# Pattern configuration
patterns:
  pack_ignore:
    - .git
    - .svn
    - .hg
    - node_modules
    - .DS_Store
    - "*.swp"
    - "*~"
    - "#*#"
    - ".env*"
    - ".terraform/"
  special_files:
    pack_config: .dodot.toml
    ignore_file: .dodotignore

# Default matchers - these define how files are processed
matchers:
  - name: install-script
    priority: 90
    trigger:
      type: filename
      data:
        pattern: install.sh
    handler:
      type: install
      data: {}
  
  - name: brewfile
    priority: 90
    trigger:
      type: filename
      data:
        pattern: Brewfile
    handler:
      type: homebrew
      data: {}
  
  - name: shell-aliases
    priority: 80
    trigger:
      type: filename
      data:
        pattern: "*aliases.sh"
    handler:
      type: shell
      data:
        placement: aliases
  
  - name: shell-profile
    priority: 80
    trigger:
      type: filename
      data:
        pattern: "profile.sh"
    handler:
      type: shell
      data:
        placement: environment
        
  - name: shell-login
    priority: 80
    trigger:
      type: filename
      data:
        pattern: "login.sh"
    handler:
      type: shell
      data:
        placement: login
  
  - name: bin-dir
    priority: 90
    trigger:
      type: directory
      data:
        pattern: bin
    handler:
      type: path
      data: {}
  
  - name: local-bin-dir
    priority: 90
    trigger:
      type: directory
      data:
        pattern: .local/bin
    handler:
      type: path
      data: {}
  
  - name: symlink-catchall
    priority: 0
    trigger:
      type: catchall
      data: {}
    handler:
      type: symlink
      data: {}