# Internal dodot system defaults
# These are embedded in the binary and provide the base configuration

[shell_integration]
bash_zsh_snippet = '[ -f "$HOME/.local/share/dodot/shell/dodot-init.sh" ] && source "$HOME/.local/share/dodot/shell/dodot-init.sh"'
bash_zsh_snippet_with_custom = '[ -f "%s/shell/dodot-init.sh" ] && source "%s/shell/dodot-init.sh"'
fish_snippet = '''
if test -f "$HOME/.local/share/dodot/shell/dodot-init.fish"
    source "$HOME/.local/share/dodot/shell/dodot-init.fish"
end'''

[file_permissions]
directory = 493  # 0755 in decimal
file = 420       # 0644 in decimal
executable = 493 # 0755 in decimal

