# dodot default configuration
# This file is embedded in the dodot binary and provides all default values
# Users can override any of these settings via their own config files

# Security settings control how dodot handles sensitive files and operations
security:
  # Files that dodot will refuse to symlink for security reasons
  # These typically contain credentials, keys, or authentication data
  protectedPaths:
    - .ssh/authorized_keys  # SSH public keys for authentication
    - .ssh/id_rsa          # SSH private key
    - .ssh/id_ed25519      # SSH private key (ed25519)
    - .gnupg               # GPG keys and configuration
    - .password-store      # Pass password manager data
    - .config/gh/hosts.yml # GitHub CLI authentication
    - .aws/credentials     # AWS access keys
    - .kube/config         # Kubernetes cluster credentials
    - .docker/config.json  # Docker registry authentication

# Patterns control which files dodot processes and which it ignores
patterns:
  # Files/directories to ignore when scanning packs
  packIgnore:
    - .git            # Git repository data
    - .svn            # Subversion repository data
    - .hg             # Mercurial repository data
    - node_modules    # Node.js dependencies (can be huge)
    - .DS_Store       # macOS folder metadata
    - "*.swp"         # Vim swap files
    - "*~"            # Emacs/general backup files
    - "#*#"           # Emacs auto-save files
  
  # Files that the catchall handler should skip
  # NOTE: This is automatically derived from specialFiles to avoid redundancy
  # The catchall handler will exclude all files listed in specialFiles
  # catchallExclude: (derived from specialFiles)
  
  # Names of special files that dodot looks for
  specialFiles:
    packConfig: .dodot.toml       # Pack configuration filename
    ignoreFile: .dodotignore      # Pack-specific ignore patterns

# Priorities determine the order in which components are processed
# Higher numbers = processed first
priorities:
  # Trigger priorities (how files are matched)
  triggers:
    filename: 100  # Exact filename matches (highest priority)
    catchall: 0    # Catches everything else (lowest priority)
  
  # Handler priorities (what actions are taken)
  handlers:
    symlink: 100   # Create symlinks (highest priority)
    path: 90       # Add to PATH
    template: 70   # Process templates
  
  # Matcher priorities (built-in file patterns)
  matchers:
    install-script: 90    # install.sh files
    brewfile: 90         # Brewfile for Homebrew
    shell-aliases: 80    # Shell alias files
    shell-profile: 80    # Shell profile files
    bin-dir: 90          # bin/ directories
    bin-path: 80         # Add bin/ to PATH
    local-bin-dir: 90    # .local/bin/ directories
    local-bin-path: 80   # Add .local/bin/ to PATH
    template: 70         # Template files
    symlink-catchall: 0  # Default symlink everything else

# Configuration for where files are linked
linkPaths:
  # Files/dirs that always go to $HOME instead of XDG directories
  # These are exceptions to the smart placement rules
  coreUnixExceptions:
    - ssh        # .ssh/ directory - SSH expects it in $HOME
    - gnupg      # .gnupg/ directory - GPG expects it in $HOME
    - aws        # .aws/ directory - AWS CLI expects it in $HOME
    - kube       # .kube/ directory - kubectl expects it in $HOME
    - docker     # .docker/ directory - Docker expects it in $HOME
    - gitconfig  # .gitconfig file - Git expects it in $HOME
    - bashrc     # .bashrc file - Bash expects it in $HOME
    - zshrc      # .zshrc file - Zsh expects it in $HOME
    - profile    # .profile file - Shell expects it in $HOME



# Shell integration snippets added to user's shell configuration
shellIntegration:
  # Snippet for Bash and Zsh shells
  bashZshSnippet: '[ -f "$HOME/.local/share/dodot/shell/dodot-init.sh" ] && source "$HOME/.local/share/dodot/shell/dodot-init.sh"'
  
  # Template version with custom path (used internally)
  bashZshSnippetWithCustom: '[ -f "%s/shell/dodot-init.sh" ] && source "%s/shell/dodot-init.sh"'
  
  # Snippet for Fish shell
  fishSnippet: |
    if test -f "$HOME/.local/share/dodot/shell/dodot-init.fish"
        source "$HOME/.local/share/dodot/shell/dodot-init.fish"
    end

# Logging configuration
logging:
  # Default log level when no -v flags are provided
  defaultLevel: warn
  
  # Time format for log timestamps (Go time format)
  timeFormat: "15:04"
  
  # Whether to use colored output in the terminal
  enableColor: true
  
  # Show source file and line numbers at this verbosity level and above
  enableCallerAtVerbosity: 2

# Matchers define patterns that map files to handlers
# These are the built-in matchers that dodot uses
matchers:
  # Runs install.sh scripts when deploying a pack
  - name: install-script
    priority: 90
    trigger:
      type: filename
      data:
        pattern: install.sh    # Matches files named install.sh
    handler:
      type: install   # Uses the install handler
      data: {}
  
  # Processes Brewfiles for Homebrew package installation
  - name: brewfile
    priority: 90
    trigger:
      type: filename
      data:
        pattern: Brewfile      # Matches files named Brewfile
    handler:
      type: homebrew    # Uses the homebrew handler
      data: {}
  
  # Sources shell alias files into the user's shell
  - name: shell-aliases
    priority: 80
    trigger:
      type: filename
      data:
        pattern: "*aliases.sh"     # Matches files ending in aliases.sh
    handler:
      type: shell   # Uses the shell handler
      data:
        placement: aliases         # Places in the aliases section
  
  # Sources shell profile configuration
  - name: shell-profile
    priority: 80
    trigger:
      type: filename
      data:
        pattern: profile.sh        # Matches files named profile.sh
    handler:
      type: shell   # Uses the shell handler
      data:
        placement: environment     # Places in the environment section
  
  # Links executable files from bin/ directories
  - name: bin-dir
    priority: 90
    trigger:
      type: directory
      data:
        pattern: bin              # Matches directories named bin
    handler:
      type: path           # Uses the path handler
      data: {}
  
  # Adds bin/ directories to the shell's PATH
  - name: bin-path
    priority: 80
    trigger:
      type: directory
      data:
        pattern: bin              # Matches directories named bin
    handler:
      type: shell_add_path # Adds directory to PATH
      data: {}
  
  # Links executable files from .local/bin/ directories
  - name: local-bin-dir
    priority: 90
    trigger:
      type: directory
      data:
        pattern: .local/bin       # Matches directories named .local/bin
    handler:
      type: path           # Uses the path handler
      data: {}
  
  # Adds .local/bin/ directories to the shell's PATH
  - name: local-bin-path
    priority: 80
    trigger:
      type: directory
      data:
        pattern: .local/bin       # Matches directories named .local/bin
    handler:
      type: shell_add_path # Adds directory to PATH
      data: {}
  
  # Default matcher that symlinks all unmatched files
  - name: symlink-catchall
    priority: 0                 # Lowest priority - runs last
    trigger:
      type: catchall       # Matches everything not caught above
      data: {}
    handler:
      type: symlink        # Creates symlinks
      data: {}