# Zsh configuration pack
name = "zsh"

# Symlink zsh configuration files
[[matchers]]
triggers = [
    { type = "FileName", pattern = ".zshrc" },
    { type = "FileName", pattern = ".zprofile" }
]
actions = [
    { type = "Symlink" }
]

# Add custom aliases to shell profile
[[matchers]]
triggers = [
    { type = "FileName", pattern = "aliases.sh" }
]
actions = [
    { type = "ShellProfile", name = "dodot-aliases" }
]