version: '3.8'

services:
  dodot-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: dodot-test:latest
    container_name: dodot-test
    stdin_open: true
    tty: true
    volumes:
      # Mount dodot binary from parent directory
      - ../bin/dodot:/usr/local/bin/dodot:ro
      # Mount sample dotfiles as read-write for testing
      - ./sample-dotfiles:/dotfiles:rw
    environment:
      - DOTFILES_ROOT=/dotfiles
    command: /bin/zsh