name: Go

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Build
      run: ./scripts/build
      env:
        SKIP_TESTS: true

    - name: Test
      run: ./scripts/test --ci
      env:
        PROJECT_ROOT: ${{ github.workspace }}

