name: Live System Tests

on:
  workflow_dispatch:
    inputs:
      verbose:
        description: 'Run tests in verbose mode'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  live-tests:
    name: Run Live System Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build development container
        uses: docker/build-push-action@v6
        with:
          context: containers/dev
          file: containers/dev/Dockerfile
          push: false
          load: true
          tags: dodot-dev:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            USER_UID=1001
            USER_GID=118
          
      - name: Run live system tests
        run: |
          # Export required env vars for docker-compose
          export USER_UID=1001
          export USER_GID=118
          # Run the tests with JUnit output using the same script as local
          ./containers/dev/run-tests.sh --formatter junit > test-results.xml
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results.xml
          retention-days: 7
          
      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        continue-on-error: true
        with:
          name: Bats Test Results
          path: test-results.xml
          reporter: java-junit
          fail-on-error: false