name: "TODO to Issue"
on: 
  push:
    branches: [main]

permissions:
  issues: write
  repository-projects: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5.0
        with:
          # IMPORTANT: There is no PATH parameter in this action!
          # Use IGNORE with regex patterns to exclude directories
          IGNORE: "vendor/.*"
          CLOSE_ISSUES: false
          AUTO_P: true
          # Note: TODO identifier cannot be disabled, it's hardcoded
          # These identifiers are ADDED to the default TODO
          IDENTIFIERS: |
            [
              {"name": "FIX", "labels": ["auto-todo"]},
              {"name": "FIXME", "labels": ["auto-todo"]},
              {"name": "ISSUE", "labels": ["auto-todo"]}
            ]
